steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ttndd-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ttndd-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://ttndd-api-122940795437.asia-southeast1.run.app/api/v1'
      - '-f'
      - 'apps/web/Dockerfile'
      - '.'
    id: build-web

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ttndd-web:$COMMIT_SHA'
    id: push-web-sha
    waitFor: ['build-web']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ttndd-web:latest'
    id: push-web-latest
    waitFor: ['build-web']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ttndd-platform'
      - '--image=gcr.io/$PROJECT_ID/ttndd-web:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_API_URL=https://ttndd-api-122940795437.asia-southeast1.run.app'
    id: deploy-web
    waitFor: ['push-web-sha', 'push-web-latest']

images:
  - 'gcr.io/$PROJECT_ID/ttndd-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ttndd-web:latest'

timeout: '600s'
